//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MfaSample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int actionsLayout = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int create = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int createuser = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int display = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int facebook = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int get = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int info = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int login = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int twitter = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int update = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int web = 2131034120;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Social = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
